# Generated by Django 6.0.2 on 2026-03-01 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancerecord_date_and_more'),
        ('core', '0004_activity_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date'], name='idx_asistencia_fecha'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['event', 'date'], name='idx_evento_fecha'),
        ),
    ]
