# Generated by Django 6.0.2 on 2026-03-01 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancerecord_idx_asistencia_fecha_and_more'),
        ('core', '0004_activity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Excursión')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_evento', models.DateField(verbose_name='Fecha del Evento')),
                ('edad_min', models.IntegerField(default=0, verbose_name='Edad Mínima')),
                ('edad_max', models.IntegerField(default=99, verbose_name='Edad Máxima')),
                ('min_asistencias', models.IntegerField(default=0, help_text='Cantidad mínima de asistencias regulares requeridas para participar', verbose_name='Asistencias Mínimas Requeridas')),
                ('estado', models.CharField(choices=[('pendiente_registro', 'Pendiente de Registro'), ('registro_cerrado', 'Registro Cerrado'), ('dia_evento', 'Día del Evento'), ('finalizado', 'Finalizado')], default='pendiente_registro', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['fecha_evento'], name='idx_excursion_fecha'), models.Index(fields=['estado', 'fecha_evento'], name='idx_excursion_estado_fecha')],
            },
        ),
        migrations.CreateModel(
            name='RegistroExcursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistio', models.BooleanField(blank=True, null=True, verbose_name='Asistió')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='attendance.excursion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursiones_registradas', to='core.beneficiary')),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'fecha_registro'], name='idx_reg_usuario_fecha'), models.Index(fields=['excursion', 'usuario'], name='idx_reg_excursion_usuario')],
                'unique_together': {('excursion', 'usuario')},
            },
        ),
    ]
