# Generated by Django 6.0.2 on 2026-03-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_excursion_registroexcursion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='estado',
            field=models.CharField(choices=[('pendiente_registro', 'Pendiente de Registro'), ('registro_cerrado', 'Registro Cerrado'), ('dia_evento', 'Día del Evento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente_registro', max_length=20, verbose_name='Estado'),
        ),
    ]
